<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MarkdownPreviewer.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarkdownPreviewer.Domain\MarkdownPreviewer.Domain.csproj" />
  </ItemGroup>

</Project>
